services:
  main:
    container_name: main
    volumes:
      - type: bind
        source: .
        target: /workspace
    ports:
      - '8888:8888'
    build:
      context: .
      dockerfile_inline: |
        FROM --platform=linux/amd64 ubuntu:22.04

        ARG DEBIAN_FRONTEND=noninteractive
        RUN apt-get update

        # bazel
        RUN apt install apt-transport-https curl gnupg -y
        RUN curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg
        RUN mv bazel-archive-keyring.gpg /usr/share/keyrings
        RUN echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list
        RUN apt update && apt install bazel -y
        RUN apt update && apt full-upgrade

        # dependencies
        RUN apt update && apt install g++ clang-format clang-tidy cppcheck valgrind -y

        RUN apt clean && rm -rf /var/lib/apt/lists/*
        WORKDIR /workspace
        CMD ["tail", "-f", "/dev/null"]
